<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NbaTeamsSeeder extends Seeder
{
    public function run()
    {
        $teams = [
            [
                'name' => 'Atlanta Hawks',
                'abbreviation' => 'ATL',
                'conference' => 'Eastern',
                'division' => 'Southeast',
                'team_mascot' => 'Harry the Hawk',
                'primary_color' => '#E03A3E',
                'secondary_color' => '#C1D32F',
                'location' => 'State Farm Arena',
                'stadium' => 'State Farm Arena',
                'city' => 'Atlanta',
                'state' => 'Georgia',
            ],
            [
                'name' => 'Boston Celtics',
                'abbreviation' => 'BOS',
                'conference' => 'Eastern',
                'division' => 'Atlantic',
                'team_mascot' => 'Lucky the Leprechaun',
                'primary_color' => '#007A33',
                'secondary_color' => '#BA9653',
                'location' => 'TD Garden',
                'stadium' => 'TD Garden',
                'city' => 'Boston',
                'state' => 'Massachusetts',
            ],
            [
                'name' => 'Brooklyn Nets',
                'abbreviation' => 'BKN',
                'conference' => 'Eastern',
                'division' => 'Atlantic',
                'team_mascot' => 'BrooklyKnight',
                'primary_color' => '#000000',
                'secondary_color' => '#FFFFFF',
                'location' => 'Barclays Center',
                'stadium' => 'Barclays Center',
                'city' => 'Brooklyn',
                'state' => 'New York',
            ],
            [
                'name' => 'Charlotte Hornets',
                'abbreviation' => 'CHA',
                'conference' => 'Eastern',
                'division' => 'Southeast',
                'team_mascot' => 'Hugo the Hornet',
                'primary_color' => '#1D1160',
                'secondary_color' => '#00788C',
                'location' => 'Spectrum Center',
                'stadium' => 'Spectrum Center',
                'city' => 'Charlotte',
                'state' => 'North Carolina',
            ],
            [
                'name' => 'Chicago Bulls',
                'abbreviation' => 'CHI',
                'conference' => 'Eastern',
                'division' => 'Central',
                'team_mascot' => 'Benny the Bull',
                'primary_color' => '#CE1141',
                'secondary_color' => '#000000',
                'location' => 'United Center',
                'stadium' => 'United Center',
                'city' => 'Chicago',
                'state' => 'Illinois',
            ],
            [
                'name' => 'Cleveland Cavaliers',
                'abbreviation' => 'CLE',
                'conference' => 'Eastern',
                'division' => 'Central',
                'team_mascot' => 'Moondog and Sir C.C.',
                'primary_color' => '#860038',
                'secondary_color' => '#041E42',
                'location' => 'Rocket Mortgage FieldHouse',
                'stadium' => 'Rocket Mortgage FieldHouse',
                'city' => 'Cleveland',
                'state' => 'Ohio',
            ],
            [
                'name' => 'Dallas Mavericks',
                'abbreviation' => 'DAL',
                'conference' => 'Western',
                'division' => 'Southwest',
                'team_mascot' => 'Champ and MavsMan',
                'primary_color' => '#00538C',
                'secondary_color' => '#002B5E',
                'location' => 'American Airlines Center',
                'stadium' => 'American Airlines Center',
                'city' => 'Dallas',
                'state' => 'Texas',
            ],
            [
                'name' => 'Denver Nuggets',
                'abbreviation' => 'DEN',
                'conference' => 'Western',
                'division' => 'Northwest',
                'team_mascot' => 'Rocky the Mountain Lion',
                'primary_color' => '#0E2240',
                'secondary_color' => '#FEC524',
                'location' => 'Ball Arena',
                'stadium' => 'Ball Arena',
                'city' => 'Denver',
                'state' => 'Colorado',
            ],
            [
                'name' => 'Detroit Pistons',
                'abbreviation' => 'DET',
                'conference' => 'Eastern',
                'division' => 'Central',
                'team_mascot' => 'Hooper',
                'primary_color' => '#C8102E',
                'secondary_color' => '#1D42BA',
                'location' => 'Little Caesars Arena',
                'stadium' => 'Little Caesars Arena',
                'city' => 'Detroit',
                'state' => 'Michigan',
            ],
            [
                'name' => 'Golden State Warriors',
                'abbreviation' => 'GSW',
                'conference' => 'Western',
                'division' => 'Pacific',
                'team_mascot' => 'Thunder',
                'primary_color' => '#1D428A',
                'secondary_color' => '#FFC72C',
                'location' => 'Chase Center',
                'stadium' => 'Chase Center',
                'city' => 'San Francisco',
                'state' => 'California',
            ],
            [
                'name' => 'Houston Rockets',
                'abbreviation' => 'HOU',
                'conference' => 'Western',
                'division' => 'Southwest',
                'team_mascot' => 'Clutch the Bear',
                'primary_color' => '#CE1141',
                'secondary_color' => '#C4CED4',
                'location' => 'Toyota Center',
                'stadium' => 'Toyota Center',
                'city' => 'Houston',
                'state' => 'Texas',
            ],
            [
                'name' => 'Indiana Pacers',
                'abbreviation' => 'IND',
                'conference' => 'Eastern',
                'division' => 'Central',
                'team_mascot' => 'Boomer',
                'primary_color' => '#002D62',
                'secondary_color' => '#FDBB30',
                'location' => 'Gainbridge Fieldhouse',
                'stadium' => 'Gainbridge Fieldhouse',
                'city' => 'Indianapolis',
                'state' => 'Indiana',
            ],
            [
                'name' => 'Los Angeles Clippers',
                'abbreviation' => 'LAC',
                'conference' => 'Western',
                'division' => 'Pacific',
                'team_mascot' => 'Chuck the Condor',
                'primary_color' => '#C8102E',
                'secondary_color' => '#1D428A',
                'location' => 'Crypto.com Arena',
                'stadium' => 'Crypto.com Arena',
                'city' => 'Los Angeles',
                'state' => 'California',
            ],
            [
                'name' => 'Los Angeles Lakers',
                'abbreviation' => 'LAL',
                'conference' => 'Western',
                'division' => 'Pacific',
                'team_mascot' => 'Jack Nicholson',
                'primary_color' => '#552583',
                'secondary_color' => '#FDB927',
                'location' => 'Crypto.com Arena',
                'stadium' => 'Crypto.com Arena',
                'city' => 'Los Angeles',
                'state' => 'California',
            ],
            [
                'name' => 'Memphis Grizzlies',
                'abbreviation' => 'MEM',
                'conference' => 'Western',
                'division' => 'Southwest',
                'team_mascot' => 'Grizz',
                'primary_color' => '#5D76A9',
                'secondary_color' => '#12173F',
                'location' => 'FedExForum',
                'stadium' => 'FedExForum',
                'city' => 'Memphis',
                'state' => 'Tennessee',
            ],
            [
                'name' => 'Miami Heat',
                'abbreviation' => 'MIA',
                'conference' => 'Eastern',
                'division' => 'Southeast',
                'team_mascot' => 'Burnie',
                'primary_color' => '#98002E',
                'secondary_color' => '#F9A01B',
                'location' => 'Kaseya Center',
                'stadium' => 'Kaseya Center',
                'city' => 'Miami',
                'state' => 'Florida',
            ],
            [
                'name' => 'Milwaukee Bucks',
                'abbreviation' => 'MIL',
                'conference' => 'Eastern',
                'division' => 'Central',
                'team_mascot' => 'Bango',
                'primary_color' => '#00471B',
                'secondary_color' => '#EEE1C6',
                'location' => 'Fiserv Forum',
                'stadium' => 'Fiserv Forum',
                'city' => 'Milwaukee',
                'state' => 'Wisconsin',
            ],
            [
                'name' => 'Minnesota Timberwolves',
                'abbreviation' => 'MIN',
                'conference' => 'Western',
                'division' => 'Northwest',
                'team_mascot' => 'Crunch the Wolf',
                'primary_color' => '#0C2340',
                'secondary_color' => '#236192',
                'location' => 'Target Center',
                'stadium' => 'Target Center',
                'city' => 'Minneapolis',
                'state' => 'Minnesota',
            ],
            [
                'name' => 'New Orleans Pelicans',
                'abbreviation' => 'NOP',
                'conference' => 'Western',
                'division' => 'Southwest',
                'team_mascot' => 'Pierre the Pelican',
                'primary_color' => '#0C2340',
                'secondary_color' => '#C8102E',
                'location' => 'Smoothie King Center',
                'stadium' => 'Smoothie King Center',
                'city' => 'New Orleans',
                'state' => 'Louisiana',
            ],
            [
                'name' => 'New York Knicks',
                'abbreviation' => 'NYK',
                'conference' => 'Eastern',
                'division' => 'Atlantic',
                'team_mascot' => 'None',
                'primary_color' => '#006BB6',
                'secondary_color' => '#F58426',
                'location' => 'Madison Square Garden',
                'stadium' => 'Madison Square Garden',
                'city' => 'New York',
                'state' => 'New York',
            ],
            [
                'name' => 'Oklahoma City Thunder',
                'abbreviation' => 'OKC',
                'conference' => 'Western',
                'division' => 'Northwest',
                'team_mascot' => 'Rumble the Bison',
                'primary_color' => '#007AC1',
                'secondary_color' => '#EF3B24',
                'location' => 'Paycom Center',
                'stadium' => 'Paycom Center',
                'city' => 'Oklahoma City',
                'state' => 'Oklahoma',
            ],
            [
                'name' => 'Orlando Magic',
                'abbreviation' => 'ORL',
                'conference' => 'Eastern',
                'division' => 'Southeast',
                'team_mascot' => 'Stuff the Magic Dragon',
                'primary_color' => '#0077C0',
                'secondary_color' => '#C4CED4',
                'location' => 'Amway Center',
                'stadium' => 'Amway Center',
                'city' => 'Orlando',
                'state' => 'Florida',
            ],
            [
                'name' => 'Philadelphia 76ers',
                'abbreviation' => 'PHI',
                'conference' => 'Eastern',
                'division' => 'Atlantic',
                'team_mascot' => 'Franklin the Dog',
                'primary_color' => '#006BB6',
                'secondary_color' => '#ED174C',
                'location' => 'Wells Fargo Center',
                'stadium' => 'Wells Fargo Center',
                'city' => 'Philadelphia',
                'state' => 'Pennsylvania',
            ],
            [
                'name' => 'Phoenix Suns',
                'abbreviation' => 'PHX',
                'conference' => 'Western',
                'division' => 'Pacific',
                'team_mascot' => 'Go the Gorilla',
                'primary_color' => '#1D1160',
                'secondary_color' => '#E56020',
                'location' => 'Footprint Center',
                'stadium' => 'Footprint Center',
                'city' => 'Phoenix',
                'state' => 'Arizona',
            ],
            [
                'name' => 'Portland Trail Blazers',
                'abbreviation' => 'POR',
                'conference' => 'Western',
                'division' => 'Northwest',
                'team_mascot' => 'Blaze the Trail Cat',
                'primary_color' => '#E03A3E',
                'secondary_color' => '#000000',
                'location' => 'Moda Center',
                'stadium' => 'Moda Center',
                'city' => 'Portland',
                'state' => 'Oregon',
            ],
            [
                'name' => 'Sacramento Kings',
                'abbreviation' => 'SAC',
                'conference' => 'Western',
                'division' => 'Pacific',
                'team_mascot' => 'Slamson the Lion',
                'primary_color' => '#5A2D81',
                'secondary_color' => '#63727A',
                'location' => 'Golden 1 Center',
                'stadium' => 'Golden 1 Center',
                'city' => 'Sacramento',
                'state' => 'California',
            ],
            [
                'name' => 'San Antonio Spurs',
                'abbreviation' => 'SAS',
                'conference' => 'Western',
                'division' => 'Southwest',
                'team_mascot' => 'The Coyote',
                'primary_color' => '#C4CED4',
                'secondary_color' => '#000000',
                'location' => 'AT&T Center',
                'stadium' => 'AT&T Center',
                'city' => 'San Antonio',
                'state' => 'Texas',
            ],
            [
                'name' => 'Toronto Raptors',
                'abbreviation' => 'TOR',
                'conference' => 'Eastern',
                'division' => 'Atlantic',
                'team_mascot' => 'The Raptor',
                'primary_color' => '#CE1141',
                'secondary_color' => '#000000',
                'location' => 'Scotiabank Arena',
                'stadium' => 'Scotiabank Arena',
                'city' => 'Toronto',
                'state' => 'Ontario',
            ],
            [
                'name' => 'Utah Jazz',
                'abbreviation' => 'UTA',
                'conference' => 'Western',
                'division' => 'Northwest',
                'team_mascot' => 'Jazz Bear',
                'primary_color' => '#002B5C',
                'secondary_color' => '#F9A01B',
                'location' => 'Vivint Arena',
                'stadium' => 'Vivint Arena',
                'city' => 'Salt Lake City',
                'state' => 'Utah',
            ],
            [
                'name' => 'Washington Wizards',
                'abbreviation' => 'WAS',
                'conference' => 'Eastern',
                'division' => 'Southeast',
                'team_mascot' => 'G-Wiz',
                'primary_color' => '#002B5C',
                'secondary_color' => '#E31837',
                'location' => 'Capital One Arena',
                'stadium' => 'Capital One Arena',
                'city' => 'Washington',
                'state' => 'District of Columbia',
            ],
        ];

        DB::table('nba_teams')->insert($teams);
    }
}
