<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NflTeam;

class NflTeamsTableSeeder extends Seeder
{
    public function run()
    {
        $teams = [
            [
                'espn_team_id' => 1, // s:20~l:28~t:1
                'uid' => 's:20~l:28~t:1',
                'is_active' => 1,
                'name' => 'Atlanta Falcons',
                'abbreviation' => 'ATL',
                'conference' => 'NFC',
                'division' => 'South',
                'team_mascot' => 'Falcons',
                'primary_color' => '#A71930',
                'secondary_color' => '#000000',
                'location' => 'Atlanta',
                'stadium' => 'Mercedes-Benz Stadium',
                'city' => 'Atlanta',
                'state' => 'Georgia',
            ],
            [
                'espn_team_id' => 2, // s:20~l:28~t:2
                'uid' => 's:20~l:28~t:2',
                'is_active' => 1,
                'name' => 'Buffalo Bills',
                'abbreviation' => 'BUF',
                'conference' => 'AFC',
                'division' => 'East',
                'team_mascot' => 'Bills',
                'primary_color' => '#00338D',
                'secondary_color' => '#D50A0A',
                'location' => 'Buffalo',
                'stadium' => 'Highmark Stadium',
                'city' => 'Buffalo',
                'state' => 'New York',
            ],
            [
                'espn_team_id' => 3, // s:20~l:28~t:3
                'uid' => 's:20~l:28~t:3',
                'is_active' => 1,
                'name' => 'Chicago Bears',
                'abbreviation' => 'CHI',
                'conference' => 'NFC',
                'division' => 'North',
                'team_mascot' => 'Bears',
                'primary_color' => '#0B1C3A',
                'secondary_color' => '#E64100',
                'location' => 'Chicago',
                'stadium' => 'Soldier Field',
                'city' => 'Chicago',
                'state' => 'Illinois',
            ],
            [
                'espn_team_id' => 4, // s:20~l:28~t:4
                'uid' => 's:20~l:28~t:4',
                'is_active' => 1,
                'name' => 'Cincinnati Bengals',
                'abbreviation' => 'CIN',
                'conference' => 'AFC',
                'division' => 'North',
                'team_mascot' => 'Bengals',
                'primary_color' => '#FB4F14',
                'secondary_color' => '#000000',
                'location' => 'Cincinnati',
                'stadium' => 'Paul Brown Stadium',
                'city' => 'Cincinnati',
                'state' => 'Ohio',
            ],
            [
                'espn_team_id' => 5, // s:20~l:28~t:5
                'uid' => 's:20~l:28~t:5',
                'is_active' => 1,
                'name' => 'Cleveland Browns',
                'abbreviation' => 'CLE',
                'conference' => 'AFC',
                'division' => 'North',
                'team_mascot' => 'Browns',
                'primary_color' => '#472A08',
                'secondary_color' => '#FF3C00',
                'location' => 'Cleveland',
                'stadium' => 'FirstEnergy Stadium',
                'city' => 'Cleveland',
                'state' => 'Ohio',
            ],
            [
                'espn_team_id' => 6, // s:20~l:28~t:6
                'uid' => 's:20~l:28~t:6',
                'is_active' => 1,
                'name' => 'Dallas Cowboys',
                'abbreviation' => 'DAL',
                'conference' => 'NFC',
                'division' => 'East',
                'team_mascot' => 'Cowboys',
                'primary_color' => '#002A5C',
                'secondary_color' => '#B0B7BC',
                'location' => 'Dallas',
                'stadium' => 'AT&T Stadium',
                'city' => 'Arlington',
                'state' => 'Texas',
            ],
            [
                'espn_team_id' => 7, // s:20~l:28~t:7
                'uid' => 's:20~l:28~t:7',
                'is_active' => 1,
                'name' => 'Denver Broncos',
                'abbreviation' => 'DEN',
                'conference' => 'AFC',
                'division' => 'West',
                'team_mascot' => 'Broncos',
                'primary_color' => '#0A2343',
                'secondary_color' => '#FC4C02',
                'location' => 'Denver',
                'stadium' => 'Empower Field at Mile High',
                'city' => 'Denver',
                'state' => 'Colorado',
            ],
            [
                'espn_team_id' => 8, // s:20~l:28~t:8
                'uid' => 's:20~l:28~t:8',
                'is_active' => 1,
                'name' => 'Detroit Lions',
                'abbreviation' => 'DET',
                'conference' => 'NFC',
                'division' => 'North',
                'team_mascot' => 'Lions',
                'primary_color' => '#0076B6',
                'secondary_color' => '#BBBBBB',
                'location' => 'Detroit',
                'stadium' => 'Ford Field',
                'city' => 'Detroit',
                'state' => 'Michigan',
            ],
            [
                'espn_team_id' => 9, // s:20~l:28~t:9
                'uid' => 's:20~l:28~t:9',
                'is_active' => 1,
                'name' => 'Green Bay Packers',
                'abbreviation' => 'GB',
                'conference' => 'NFC',
                'division' => 'North',
                'team_mascot' => 'Packers',
                'primary_color' => '#204E32',
                'secondary_color' => '#FFB612',
                'location' => 'Green Bay',
                'stadium' => 'Lambeau Field',
                'city' => 'Green Bay',
                'state' => 'Wisconsin',
            ],
            [
                'espn_team_id' => 10, // s:20~l:28~t:10
                'uid' => 's:20~l:28~t:10',
                'is_active' => 1,
                'name' => 'Tennessee Titans',
                'abbreviation' => 'TEN',
                'conference' => 'AFC',
                'division' => 'South',
                'team_mascot' => 'Titans',
                'primary_color' => '#4B92DB',
                'secondary_color' => '#002A5C',
                'location' => 'Tennessee',
                'stadium' => 'Nissan Stadium',
                'city' => 'Nashville',
                'state' => 'Tennessee',
            ],
            [
                'espn_team_id' => 11, // s:20~l:28~t:11
                'uid' => 's:20~l:28~t:11',
                'is_active' => 1,
                'name' => 'Indianapolis Colts',
                'abbreviation' => 'IND',
                'conference' => 'AFC',
                'division' => 'South',
                'team_mascot' => 'Colts',
                'primary_color' => '#003B75',
                'secondary_color' => '#FFFFFF',
                'location' => 'Indianapolis',
                'stadium' => 'Lucas Oil Stadium',
                'city' => 'Indianapolis',
                'state' => 'Indiana',
            ],
            [
                'espn_team_id' => 12, // s:20~l:28~t:12
                'uid' => 's:20~l:28~t:12',
                'is_active' => 1,
                'name' => 'Kansas City Chiefs',
                'abbreviation' => 'KC',
                'conference' => 'AFC',
                'division' => 'West',
                'team_mascot' => 'Chiefs',
                'primary_color' => '#E31837',
                'secondary_color' => '#FFB612',
                'location' => 'Kansas City',
                'stadium' => 'Arrowhead Stadium',
                'city' => 'Kansas City',
                'state' => 'Missouri',
            ],
            [
                'espn_team_id' => 13, // s:20~l:28~t:13
                'uid' => 's:20~l:28~t:13',
                'is_active' => 1,
                'name' => 'Las Vegas Raiders',
                'abbreviation' => 'LV',
                'conference' => 'AFC',
                'division' => 'West',
                'team_mascot' => 'Raiders',
                'primary_color' => '#000000',
                'secondary_color' => '#A5ACAF',
                'location' => 'Las Vegas',
                'stadium' => 'Allegiant Stadium',
                'city' => 'Las Vegas',
                'state' => 'Nevada',
            ],
            [
                'espn_team_id' => 14, // s:20~l:28~t:14
                'uid' => 's:20~l:28~t:14',
                'is_active' => 1,
                'name' => 'Los Angeles Rams',
                'abbreviation' => 'LAR',
                'conference' => 'NFC',
                'division' => 'West',
                'team_mascot' => 'Rams',
                'primary_color' => '#003594',
                'secondary_color' => '#FFD100',
                'location' => 'Los Angeles',
                'stadium' => 'SoFi Stadium',
                'city' => 'Inglewood',
                'state' => 'California',
            ],
            [
                'espn_team_id' => 15, // s:20~l:28~t:15
                'uid' => 's:20~l:28~t:15',
                'is_active' => 1,
                'name' => 'Miami Dolphins',
                'abbreviation' => 'MIA',
                'conference' => 'AFC',
                'division' => 'East',
                'team_mascot' => 'Dolphins',
                'primary_color' => '#008E97',
                'secondary_color' => '#FC4C02',
                'location' => 'Miami Gardens',
                'stadium' => 'Hard Rock Stadium',
                'city' => 'Miami',
                'state' => 'Florida',
            ],
            [
                'espn_team_id' => 16, // s:20~l:28~t:16
                'uid' => 's:20~l:28~t:16',
                'is_active' => 1,
                'name' => 'Minnesota Vikings',
                'abbreviation' => 'MIN',
                'conference' => 'NFC',
                'division' => 'North',
                'team_mascot' => 'Vikings',
                'primary_color' => '#4F2683',
                'secondary_color' => '#FFC62F',
                'location' => 'Minneapolis',
                'stadium' => 'U.S. Bank Stadium',
                'city' => 'Minneapolis',
                'state' => 'Minnesota',
            ],
            [
                'espn_team_id' => 17, // s:20~l:28~t:17
                'uid' => 's:20~l:28~t:17',
                'is_active' => 1,
                'name' => 'New England Patriots',
                'abbreviation' => 'NE',
                'conference' => 'AFC',
                'division' => 'East',
                'team_mascot' => 'Patriots',
                'primary_color' => '#002A5C',
                'secondary_color' => '#C60C30',
                'location' => 'Foxborough',
                'stadium' => 'Gillette Stadium',
                'city' => 'New England',
                'state' => 'Massachusetts',
            ],
            [
                'espn_team_id' => 18, // s:20~l:28~t:18
                'uid' => 's:20~l:28~t:18',
                'is_active' => 1,
                'name' => 'New Orleans Saints',
                'abbreviation' => 'NO',
                'conference' => 'NFC',
                'division' => 'South',
                'team_mascot' => 'Saints',
                'primary_color' => '#D3BC8D',
                'secondary_color' => '#000000',
                'location' => 'New Orleans',
                'stadium' => 'Caesars Superdome',
                'city' => 'New Orleans',
                'state' => 'Louisiana',
            ],
            [
                'espn_team_id' => 19, // s:20~l:28~t:19
                'uid' => 's:20~l:28~t:19',
                'is_active' => 1,
                'name' => 'New York Giants',
                'abbreviation' => 'NYG',
                'conference' => 'NFC',
                'division' => 'East',
                'team_mascot' => 'Giants',
                'primary_color' => '#003C7F',
                'secondary_color' => '#C9243F',
                'location' => 'East Rutherford',
                'stadium' => 'MetLife Stadium',
                'city' => 'New York',
                'state' => 'New Jersey',
            ],
            [
                'espn_team_id' => 20, // s:20~l:28~t:20
                'uid' => 's:20~l:28~t:20',
                'is_active' => 1,
                'name' => 'New York Jets',
                'abbreviation' => 'NYJ',
                'conference' => 'AFC',
                'division' => 'East',
                'team_mascot' => 'Jets',
                'primary_color' => '#115740',
                'secondary_color' => '#FFFFFF',
                'location' => 'East Rutherford',
                'stadium' => 'MetLife Stadium',
                'city' => 'New York',
                'state' => 'New Jersey',
            ],
            [
                'espn_team_id' => 21, // s:20~l:28~t:21
                'uid' => 's:20~l:28~t:21',
                'is_active' => 1,
                'name' => 'Philadelphia Eagles',
                'abbreviation' => 'PHI',
                'conference' => 'NFC',
                'division' => 'East',
                'team_mascot' => 'Eagles',
                'primary_color' => '#06424D',
                'secondary_color' => '#000000',
                'location' => 'Philadelphia',
                'stadium' => 'Lincoln Financial Field',
                'city' => 'Philadelphia',
                'state' => 'Pennsylvania',
            ],
            [
                'espn_team_id' => 22, // s:20~l:28~t:22
                'uid' => 's:20~l:28~t:22',
                'is_active' => 1,
                'name' => 'Arizona Cardinals',
                'abbreviation' => 'ARI',
                'conference' => 'NFC',
                'division' => 'West',
                'team_mascot' => 'Cardinals',
                'primary_color' => '#A40227',
                'secondary_color' => '#FFFFFF',
                'location' => 'Glendale',
                'stadium' => 'State Farm Stadium',
                'city' => 'Phoenix',
                'state' => 'Arizona',
            ],
            [
                'espn_team_id' => 23, // s:20~l:28~t:23
                'uid' => 's:20~l:28~t:23',
                'is_active' => 1,
                'name' => 'Pittsburgh Steelers',
                'abbreviation' => 'PIT',
                'conference' => 'AFC',
                'division' => 'North',
                'team_mascot' => 'Steelers',
                'primary_color' => '#000000',
                'secondary_color' => '#FFB612',
                'location' => 'Pittsburgh',
                'stadium' => 'Heinz Field',
                'city' => 'Pittsburgh',
                'state' => 'Pennsylvania',
            ],
            [
                'espn_team_id' => 24, // s:20~l:28~t:24
                'uid' => 's:20~l:28~t:24',
                'is_active' => 1,
                'name' => 'Los Angeles Chargers',
                'abbreviation' => 'LAC',
                'conference' => 'AFC',
                'division' => 'West',
                'team_mascot' => 'Chargers',
                'primary_color' => '#0080C6',
                'secondary_color' => '#FFC20E',
                'location' => 'Los Angeles',
                'stadium' => 'SoFi Stadium',
                'city' => 'Inglewood',
                'state' => 'California',
            ],
            [
                'espn_team_id' => 25, // s:20~l:28~t:25
                'uid' => 's:20~l:28~t:25',
                'is_active' => 1,
                'name' => 'San Francisco 49ers',
                'abbreviation' => 'SF',
                'conference' => 'NFC',
                'division' => 'West',
                'team_mascot' => '49ers',
                'primary_color' => '#AA0000',
                'secondary_color' => '#B3995D',
                'location' => 'Santa Clara',
                'stadium' => 'Levi\'s Stadium',
                'city' => 'San Francisco',
                'state' => 'California',
            ],
            [
                'espn_team_id' => 26, // s:20~l:28~t:26
                'uid' => 's:20~l:28~t:26',
                'is_active' => 1,
                'name' => 'Seattle Seahawks',
                'abbreviation' => 'SEA',
                'conference' => 'NFC',
                'division' => 'West',
                'team_mascot' => 'Seahawks',
                'primary_color' => '#002A5C',
                'secondary_color' => '#69BE28',
                'location' => 'Seattle',
                'stadium' => 'Lumen Field',
                'city' => 'Seattle',
                'state' => 'Washington',
            ],
            [
                'espn_team_id' => 27, // s:20~l:28~t:27
                'uid' => 's:20~l:28~t:27',
                'is_active' => 1,
                'name' => 'Tampa Bay Buccaneers',
                'abbreviation' => 'TB',
                'conference' => 'NFC',
                'division' => 'South',
                'team_mascot' => 'Buccaneers',
                'primary_color' => '#BD1C36',
                'secondary_color' => '#3E3A35',
                'location' => 'Tampa',
                'stadium' => 'Raymond James Stadium',
                'city' => 'Tampa',
                'state' => 'Florida',
            ],
            [
                'espn_team_id' => 28, // s:20~l:28~t:28
                'uid' => 's:20~l:28~t:28',
                'is_active' => 1,
                'name' => 'Washington Commanders',
                'abbreviation' => 'WSH',
                'conference' => 'NFC',
                'division' => 'East',
                'team_mascot' => 'Commanders',
                'primary_color' => '#5A1414',
                'secondary_color' => '#FFB612',
                'location' => 'Landover',
                'stadium' => 'FedEx Field',
                'city' => 'Washington',
                'state' => 'D.C.',
            ],
            [
                'espn_team_id' => 29, // s:20~l:28~t:29
                'uid' => 's:20~l:28~t:29',
                'is_active' => 1,
                'name' => 'Carolina Panthers',
                'abbreviation' => 'CAR',
                'conference' => 'NFC',
                'division' => 'South',
                'team_mascot' => 'Panthers',
                'primary_color' => '#0085CA',
                'secondary_color' => '#000000',
                'location' => 'Charlotte',
                'stadium' => 'Bank of America Stadium',
                'city' => 'Charlotte',
                'state' => 'North Carolina',
            ],
            [
                'espn_team_id' => 30, // s:20~l:28~t:30
                'uid' => 's:20~l:28~t:30',
                'is_active' => 1,
                'name' => 'Jacksonville Jaguars',
                'abbreviation' => 'JAX',
                'conference' => 'AFC',
                'division' => 'South',
                'team_mascot' => 'Jaguars',
                'primary_color' => '#007487',
                'secondary_color' => '#D7A22A',
                'location' => 'Jacksonville',
                'stadium' => 'TIAA Bank Field',
                'city' => 'Jacksonville',
                'state' => 'Florida',
            ],
            [
                'espn_team_id' => 33, // s:20~l:28~t:33
                'uid' => 's:20~l:28~t:33',
                'is_active' => 1,
                'name' => 'Baltimore Ravens',
                'abbreviation' => 'BAL',
                'conference' => 'AFC',
                'division' => 'North',
                'team_mascot' => 'Ravens',
                'primary_color' => '#29126F',
                'secondary color' => '#000000',
                'location' => 'Baltimore',
                'stadium' => 'M&T Bank Stadium',
                'city' => 'Baltimore',
                'state' => 'Maryland',
            ],
            [
                'espn_team_id' => 34, // s:20~l:28~t:34
                'uid' => 's:20~l:28~t:34',
                'is_active' => 1,
                'name' => 'Houston Texans',
                'abbreviation' => 'HOU',
                'conference' => 'AFC',
                'division' => 'South',
                'team_mascot' => 'Texans',
                'primary color' => '#00143F',
                'secondary_color' => '#C41230',
                'location' => 'Houston',
                'stadium' => 'NRG Stadium',
                'city' => 'Houston',
                'state' => 'Texas',
            ],
            // Add any additional teams as necessary...
        ];

        foreach ($teams as $team) {
            NflTeam::create($team);
        }
    }
}
