{{$Data->name}}
{{$teamData->team->location}}
{{$teamData->team->nickname}}
{{$teamData->team->abbreviation}}
{{$teamData->team->color}}
{{$teamData->team->alternateColor}}
{{$teamData->team->logo}}
{{$teamData->team->conference}}
{{$teamData->team->division}}
{{$teamData->team->wins}}
{{$teamData->team->losses}}
{{$teamData->team->ties}}
{{$teamData->team->winPercentage}}
{{$teamData->team->pointsFor}}
{{$teamData->team->pointsAgainst}}
{{$teamData->team->points}}
{{$teamData->team->rank}}
{{$teamData->team->streak}}
{{$teamData->team->streakType}}
{{$teamData->team->streakTotal}}
{{$teamData->team->standing}}
{{$teamData->team->standingType}}
{{$teamData->team->standingConference}}
{{$teamData->team->standingDivision}}
{{$teamData->team->standingGamesBack}}
{{$teamData->team->standingGamesBackWildcard}}
{{$teamData->team->standingGamesPlayed}}
{{$teamData->team->standingGamesRemaining}}
{{$teamData->team->standingHome}}
{{$teamData->team->standingAway}}
{{$teamData->team->standingConferenceGamesBack}}
{{$teamData->team->standingDivisionGamesBack}}
{{$teamData->team->standingClinchedPlayoffBirth}}
{{$teamData->team->standingClinchedDivision}}
{{$teamData->team->standingClinchedConference}}
{{$teamData->team->standingClinchedHomeField}}
{{$teamData->team->standingClinchedFirstRoundBye}}
{{$teamData->team->standingClinchedTopSeed}}
{{$teamData->team->standingEliminated}}
{{$teamData->team->standingMagicNumber}}
{{$teamData->team->standingWins}}
{{$teamData->team->standingLosses}}
{{$teamData->team->standingTies}}
{{$teamData->team->standingWinPercentage}}
{{$teamData->team->standingPointsFor}}
{{$teamData->team->standingPointsAgainst}}
{{$teamData->team->standingPoints}}
{{$teamData->team->standingRank}}
{{$teamData->team->standingStreak}}
{{$teamData->team->standingStreakType}}
{{$teamData->team->standingStreakTotal}}
{{$teamData->team->standingGamesBack}}
