<?php

return [
    'base_uri' => 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/',
    'alternate_base_uris' => [
        'core' => 'https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/',
        'cdn' => 'https://cdn.espn.com/core/nfl/',
    ],
    'endpoints' => [
        'teams' => [
            'all' => '/teams',
            'details' => '/teams/{teamId}',
            'athletes' => '/teams/{teamId}/athletes',
            'events' => '/teams/{teamId}/events',
            'coaches' => '/teams/{teamId}/coaches',
        ],
        'franchises' => [
            'all' => '/franchises',
        ],
        'events' => [
            'all' => '/scoreboard?limit=1000&dates={YEAR}',
            'details' => '/summary?event={eventId}',
            'plays' => '/events/{eventId}/competitions/{eventId}/plays',
            'probabilities' => '/events/{eventId}/competitions/{eventId}/probabilities',
            'odds' => '/events/{eventId}/competitions/{eventId}/odds',
        ],
        'athletes' => [
            'all' => '/athletes?limit=1000&active=true',
            'details' => '/athletes/{athleteId}',
            'splits' => '/athletes/{athleteId}/splits',
            'stats' => '/athletes/{athleteId}/stats',
            'eventlog' => '/seasons/{year}/athletes/{athleteId}/eventlog',
            'news' => '/athletes/{athleteId}/news',
        ],
        'seasons' => [
            'team_athletes' => '/seasons/{year}/teams/{teamId}/athletes',
            'team_events' => '/seasons/{year}/teams/{teamId}/events',
            'athlete_stats' => '/seasons/{year}/athletes/{athleteId}/statistics',
            'league_leaders' => '/seasons/{year}/leagues/nfl/leaders',
        ],
        'games' => [
            'summary' => '/events/{gameId}/summary',
            'plays' => '/events/{gameId}/competitions/{gameId}/plays',
            'probabilities' => '/events/{gameId}/competitions/{gameId}/probabilities',
            'odds' => '/events/{gameId}/competitions/{gameId}/odds',
            'athletes' => '/events/{gameId}/competitions/{gameId}/athletes',
        ],
        'odds' => [
            'probabilities' => '/events/{eventId}/competitions/{eventId}/probabilities',
            'odds' => '/events/{eventId}/competitions/{eventId}/odds',
        ],
        'stats' => [
            'league' => '/sports/football/leagues/nfl/statistics',
            'team' => '/seasons/{year}/teams/{teamId}/statistics',
        ],
        'leaders' => [
            'league' => '/sports/football/leagues/nfl/leaders',
            'season' => '/seasons/{year}/leagues/nfl/leaders',
        ],
        'calendar' => [
            'default' => '/calendar',
            'year' => '/calendar?year={year}',
        ],
    ],
    'urls' => [
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/22?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/1?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/33?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/2?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/29?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/3?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/4?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/5?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/6?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/7?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/8?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/9?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/10?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/34?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/11?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/30?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/12?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/24?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/14?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/13?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/15?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/16?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/17?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/18?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/19?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/20?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/21?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/25?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/26?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/27?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/28?lang=en&region=us',
        'http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/23?lang=en&region=us',
    ],
];
